// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GUI.Models;

public partial class AdminEntity
{
    public string AdminId { get; set; }

    public string AdminAccount { get; set; }

    public string AdminPassword { get; set; }

    public int? AdminLevel { get; set; }
}