// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GUI.Models;

public partial class BagEntity
{
    public string BagId { get; set; }

    public int? Capacity { get; set; }

    public string BagData { get; set; }

    public virtual ICollection<CharacterEntity> CharacterEntities { get; set; } = new List<CharacterEntity>();
}