// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GUI.Models;

public partial class CharacterEntity
{
    public string PlayerId { get; set; }

    public string CharacterId { get; set; }

    public int? Gender { get; set; }

    public int? Exp { get; set; }

    public string Profession { get; set; }

    public int? Hp { get; set; }

    public int? Attack { get; set; }

    public float? PhysicalResist { get; set; }

    public string EquipName { get; set; }

    public string EquipId { get; set; }

    public string BagId { get; set; }

    public string HashId { get; set; }

    public virtual BagEntity Bag { get; set; }

    public virtual CharacterEquipEntity Equip { get; set; }
}