// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GUI.Models;

public partial class CharacterEquipEntity
{
    public string EquipId { get; set; }

    public string EquipName { get; set; }

    public string EquipType { get; set; }

    public int? Hp { get; set; }

    public int? Attack { get; set; }

    public int? Def { get; set; }

    public float? PhysResist { get; set; }

    public virtual ICollection<CharacterEntity> CharacterEntities { get; set; } = new List<CharacterEntity>();

    public virtual ShopInfoEntity ShopInfoEntity { get; set; }
}