// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GUI.Models;

public partial class PlayerBehaviorEntity
{
    public string PlayerId { get; set; }

    public int BehaviorType { get; set; }

    public DateTime BehaviorTime { get; set; }

    public string BehaviorDetail { get; set; }
}