// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GUI.Models;

public partial class PlayerCharacter
{
    public string PlayerId { get; set; }

    public string CharacterId { get; set; }
}