// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GUI.Models;

public partial class PlayerInfoEntity
{
    public string PlayerId { get; set; }

    public string CharacterId { get; set; }

    public string Account { get; set; }

    public string Nickname { get; set; }

    public int Gender { get; set; }

    public int Age { get; set; }
}