// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GUI.Models;

public partial class ShopInfoEntity
{
    public string ItemName { get; set; }

    public string ItemId { get; set; }

    public string ItemDescription { get; set; }

    public int? ItemNum { get; set; }

    public int? ItemCost { get; set; }

    public virtual CharacterEquipEntity Item { get; set; }
}